
ALTER TABLE payment_config
  ADD COLUMN IF NOT EXISTS wechat_rate  NUMERIC(10,4) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS alipay_rate  NUMERIC(10,4) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS paypay_rate  NUMERIC(10,4) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS cash_rate    NUMERIC(10,4) NOT NULL DEFAULT 1;
